FROM debian:latest
MAINTAINER Miguel Macagno

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip\
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install Flask

#COPY src /src
WORKDIR /src

EXPOSE 80

ENTRYPOINT ["/usr/bin/python3","inicio.py"]
